### ISSUE TITLE
[story]: Form Crates Update and Issues

### ISSUE THREAD

**Issue by NewBetaPrime** [PixelmonToGo/ptg-issues#12]
### Who does this affect?

As a player that purchases the form key.

### What do they want?

To be able to have access to all forms and have forms work.

### Why do they want this?

So that players can get what they paid for.

### How did this begin?

When it was reported by the community manager to the founder.

### When is this resolved?

When the crate keys give said player any form of pokemon and do not malfunction.

### What is the outcome of the resolution?

For players to be able to receive what they had paid for without breaking.

**Comment by LooterToGo** [comment]
Which Form is not working? @NewBetaPrime

**Comment by NewBetaPrime** [comment]
Check the names of certain Pokémon at the moment the only one I’ve seen is
Larvesta.
It’s misspelled as Larvista and without the proper naming the command most
likely isn’t going through for players. Please make sure to check for
spelling errors on the new released forms.
