### ISSUE TITLE
[story]: /hunt does not work

### ISSUE THREAD

**Issue by NewBetaPrime** [PixelmonToGo/ptg-issues#2]
### Who does this affect?

Players who wish to use /hunt.

### What do they want?

To be able to use the application for /hunt to earn more rewards.

### Why do they want this?

To be able to use what /hunt provides to the players.

### How did this begin?

Players reporting to community manager in game of /hunt not working properly.

### When is this resolved?

When the players can use /hunt again.

### What is the outcome of the resolution?

For the players to be able to have access to /hunt again.

**Comment by LooterToGo** [comment]
Issue Resolved
