### ISSUE TITLE
[story]: /spawnanultra does not exist

### ISSUE THREAD

**Issue by NewBetaPrime** [PixelmonToGo/ptg-issues#3]
### Who does this affect?

5 Star Rank players that want to use the `/spawnanultra` command.

### What do they want?

To be able to use the `/spawnanultra` command.

### Why do they want this?

So that 5 Star ranked players can use the command that they are entitled to.

### How did this begin?

When reported to the community manager by the player base in-game.

### When is this resolved?

When 5 Star ranked players have access to the command `/spawnanultra`.

### What is the outcome of the resolution?

For `/spawnanultra` to work for 5 Star ranked players.

**Comment by LooterToGo** [comment]
Fix has been queued for next update.
