### ISSUE TITLE
[story]: /wt does not work properly

### ISSUE THREAD

**Issue by NewBetaPrime** [PixelmonToGo/ptg-issues#4]
### Who does this affect?

As a player that uses `/wt` command.

### What do they want?

To be able to use `/wt` command properly.

### Why do they want this?

To make trading more enjoyable amongst other players.

### How did this begin?

When the community manager was notified by the player.

### When is this resolved?

When the players can use the `/wt` command properly.

### What is the outcome of the resolution?

For the `/wt` command to be properly usable by the players.

**Comment by LooterToGo** [comment]
Fix has been queued for next update.
