### ISSUE TITLE
[story]: Pokeloots and shrines are now unusable on others' claims

### ISSUE THREAD

**Issue by NewBetaPrime** [PixelmonToGo/ptg-issues#5]
### Who does this affect?

As a player that plays the game.

### What do they want?

To be able to have universal access to shrines and pokeloots in the overworld.

### Why do they want this?

To have access to shrines and prevent claim issues.

### How did this begin?

When the community manager was informed by a player in-game.

### When is this resolved?

When players can loot pokeloots and use shrines without claims blocking.

### What is the outcome of the resolution?

For players to be able to access shrines and pokeloots.

**Comment by LooterToGo** [comment]
Has been resolved.
