### ISSUE TITLE
[story]: Fix Pokemon TM Summary

### ISSUE THREAD

**Issue by NewBetaPrime** [PixelmonToGo/ptg-issues#6]
### Who does this affect?

Players' pokemon's TM summary

### What do they want?

To be able to access their summary fully

### Why do they want this?

To see the players' pokemon's learnable moves

### How did this begin?

When players in-game informed the community manager.

### When is this resolved?

When players have full access to their TM summary of their pokemon.

### What is the outcome of the resolution?

For players to be able to see the TM summary of their pokemon.

**Comment by LooterToGo** [comment]
Can you explain what a TM Summary is? @NewBetaPrime
