### ISSUE TITLE
[story]: Two Star key does not work

### ISSUE THREAD

**Issue by NewBetaPrime** [PixelmonToGo/ptg-issues#7]
### Who does this affect?

As a 2 Star ranked player.

### What do they want?

To be able to receive their 2 Star ranked key from `/kits` `/twostar`.

### Why do they want this?

So that 2 Star ranked players can use the command that they are entitled to.

### How did this begin?

When reported to the community manager by the player base in-game.

### When is this resolved?

When 2 Star ranked players have access to the key from the command `/twostar`.

### What is the outcome of the resolution?

For 2 Star ranked players to have their key from `/kits` `/twostar`.

**Comment by LooterToGo** [comment]
Issue is resolved.
