### ISSUE TITLE
[story]: In game shops are down

### ISSUE THREAD

**Issue by NewBetaPrime** [PixelmonToGo/ptg-issues#8]
### Who does this affect?

As a player that uses the in-game store.

### What do they want?

A functional in-game shop.

### Why do they want this?

To earn in-game cash and spend it.

### How did this begin?

When the community manager was informed by a player in the game.

### When is this resolved?

When the in-game shops are fully accessible to buy and sell in-game for players.

### What is the outcome of the resolution?

For players to be able to use the in-game shop again.

**Comment by LooterToGo** [comment]
Issue Resolved.
